name: Update Profile README

on:
  schedule:
    - cron: "5 0 * * *" # Chạy mỗi ngày vào lúc 00:05 AM UTC (7:05 AM +07)

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-grid-snake.svg
            assets/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Update README
        run: |
          echo "### GitHub Stats" >> README.md
          echo "" >> README.md
          echo '<img src="assets/github-contribution-grid-snake.svg" alt="GitHub Contribution Snake" width="500" />' >> README.md
          echo "" >> README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update contribution snake"
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
