name: Generate Snake

on:
  schedule:
    # Run twice a day
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generate the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: thnhan3
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Commit and push the changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "thnhan3"
          git config --global user.email "huunhantran10@gmail.com"
          git add .
          git commit -m "Update snake picture"
          git push origin master

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
