name: Generate Snake

on:
  schedule:
    # Run twice a day
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
      with:
        # github user name to read the contribution graph from (**required**)
        # using action context var `github.repository_owner` or specified user
        github_user_name: thnhan3

        # list of files to generate.
        # one file per line. Each output can be customized with options as query string.
        #
        #  supported options:
        #  - palette:     A preset of color, one of [github, github-dark, github-light]
        #  - color_snake: Color of the snake
        #  - color_dots:  Coma separated list of dots color.
        #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
        #                 Exactly 5 colors are expected.
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit and push the changes
      - name: Commit and Push changes
        run: |
          git config --global user.name "thnhan3"
          git config --global user.email "huunhantran10@gmail.com"
          git add .
          git commit -m "Update snake picture"
          git push origin master

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
